function Recipes() {
    return (
        <div style={{ padding: "30px" }}>
            <h1>🍎 Recipes</h1>

            <p>
                Discover personalized recipe recommendations based on your
                health profile and wellness goals.
            </p>

            <div
                style={{
                    marginTop: "30px",
                    background: "white",
                    padding: "30px",
                    borderRadius: "10px",
                    boxShadow: "0 2px 5px rgba(0,0,0,.15)"
                }}
            >
                <h2>Personalized Recommendations</h2>

                <p>
                    Recipe recommendations will appear here once they are
                    generated by the recommendation engine.
                </p>

                <p style={{ color: "#666" }}>
                    Complete your Health Profile to receive personalized meal
                    suggestions.
                </p>
            </div>
        </div>
    );
}

export default Recipes;